name: Render Readme
on:
  push:
    branches:
      - "dev"

  # Schedule updates (“Runs at 00:00 UTC every day”)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: iamrony777
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Calcutta
          config_display: large
          plugin_lines: yes
          clean_workflows: success

      - name: Wakatime
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: wakatime.svg
          plugin_wakatime: yes
          plugin_wakatime_url: https://wakatime.pi-home.tk
          plugin_wakatime_languages_ignored: Other
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 14
          config_display: large
      
      - name: YoutubeMusic
        uses: lowlighter/metrics@latest
        with: 
          base: ""
          filename: music.svg
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_token: ${{ secrets.YOUTUBE_COOKIE }}
          plugin_music_mode: recent
          plugin_music_limit: 1
          plugin_music_top_type: tracks
